version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
      vitest:
        patterns:
          - 'vitest*'
          - '@vitest/*'
      types:
        patterns:
          - '@types/*'
    labels:
      - 'type:chore'
      - 'area:tooling'
  - package-ecosystem: npm
    directory: /playground
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels:
      - 'type:chore'
      - 'area:tooling'
  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    labels:
      - 'type:chore'
      - 'area:tooling'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - 'type:chore'
      - 'area:ci'
