import { PDFME_VERSION } from './version.js';
import {
  MM_TO_PT_RATIO,
  PT_TO_MM_RATIO,
  PT_TO_PX_RATIO,
  BLANK_PDF,
  BLANK_A4_PDF,
  CUSTOM_A4_PDF,
  ZOOM,
  DEFAULT_FONT_NAME,
} from './constants.js';
import type {
  ChangeSchemaItem,
  ChangeSchemas,
  SchemaPageArray,
  PropPanel,
  PropPanelSchema,
  PropPanelWidgetProps,
  PDFRenderProps,
  LayoutMeasureProps,
  LayoutMeasureResult,
  LayoutFragment,
  LayoutAnchorPoint,
  TextOverflow,
  TextLineRange,
  SchemaLayoutRule,
  HorizontalAnchorRule,
  VerticalAnchorRule,
  AnchorRef,
  DataFormatHint,
  DesignDataField,
  DesignDataPackage,
  DesignDataSchema,
  DesignDataVariable,
  SampleDataPanelOptions,
  SchemaBinding,
  SchemaBindingColumn,
  Mode,
  UIRenderProps,
  Plugin,
  Lang,
  Dict,
  Size,
  Schema,
  SchemaForUI,
  Font,
  ColorType,
  BasePdf,
  BlankPdf,
  CustomPdf,
  StationeryPdf,
  Template,
  CommonOptions,
  GeneratorOptions,
  Plugins,
  PluginRegistry,
  GenerateProps,
  UIOptions,
  UIProps,
  PreviewProps,
  DesignerProps,
} from './types.js';
import {
  cloneDeep,
  getFallbackFontName,
  getDefaultFont,
  getB64BasePdf,
  b64toUint8Array,
  checkFont,
  checkInputs,
  checkUIOptions,
  checkTemplate,
  checkUIProps,
  checkPreviewProps,
  checkDesignerProps,
  checkGenerateProps,
  mm2pt,
  pt2mm,
  pt2px,
  px2mm,
  isHexValid,
  getInputFromTemplate,
  isBlankPdf,
  isStationeryPdf,
  treatsLikeBlank,
  isUrlSafeToFetch,
} from './helper.js';
import {
  getDynamicTemplate,
  getDynamicHeights,
  PAGE_BREAK_SCHEMA_TYPE,
} from './dynamicTemplate.js';
import { resolveAnchorTargetPoint } from './anchorLayout.js';
import type { AnchorAxis, ResolvedAnchorTarget } from './anchorLayout.js';
import { replacePlaceholders } from './expression.js';
import type { ReplacePlaceholdersOptions } from './expression.js';
import { pluginRegistry } from './pluginRegistry.js';
import {
  formatDesignDataValue,
  getDesignDataInput,
  getDesignDataVariables,
  getTableBindingPreview,
  getValueByPath,
  resolveSchemaValue,
} from './dataBinding.js';

export {
  PDFME_VERSION,
  MM_TO_PT_RATIO,
  PT_TO_MM_RATIO,
  PT_TO_PX_RATIO,
  BLANK_PDF,
  BLANK_A4_PDF,
  CUSTOM_A4_PDF,
  ZOOM,
  DEFAULT_FONT_NAME,
  cloneDeep,
  getFallbackFontName,
  getDefaultFont,
  getB64BasePdf,
  b64toUint8Array,
  mm2pt,
  pt2mm,
  pt2px,
  px2mm,
  isHexValid,
  getInputFromTemplate,
  isBlankPdf,
  isStationeryPdf,
  treatsLikeBlank,
  getDynamicTemplate,
  getDynamicHeights,
  PAGE_BREAK_SCHEMA_TYPE,
  resolveAnchorTargetPoint,
  formatDesignDataValue,
  getDesignDataInput,
  getDesignDataVariables,
  getTableBindingPreview,
  getValueByPath,
  resolveSchemaValue,
  replacePlaceholders,
  checkFont,
  checkInputs,
  checkUIOptions,
  checkTemplate,
  checkUIProps,
  checkPreviewProps,
  checkDesignerProps,
  checkGenerateProps,
  pluginRegistry,
  isUrlSafeToFetch,
};

export type {
  Lang,
  Dict,
  Size,
  Schema,
  SchemaForUI,
  Font,
  ColorType,
  BasePdf,
  BlankPdf,
  CustomPdf,
  StationeryPdf,
  Template,
  CommonOptions,
  GeneratorOptions,
  Plugin,
  Plugins,
  PluginRegistry,
  GenerateProps,
  UIOptions,
  UIProps,
  PreviewProps,
  DesignerProps,
  ChangeSchemaItem,
  ChangeSchemas,
  SchemaPageArray,
  PropPanel,
  PropPanelSchema,
  PropPanelWidgetProps,
  PDFRenderProps,
  LayoutMeasureProps,
  LayoutMeasureResult,
  LayoutFragment,
  LayoutAnchorPoint,
  TextOverflow,
  TextLineRange,
  SchemaLayoutRule,
  HorizontalAnchorRule,
  VerticalAnchorRule,
  AnchorRef,
  DataFormatHint,
  DesignDataField,
  DesignDataPackage,
  DesignDataSchema,
  DesignDataVariable,
  SampleDataPanelOptions,
  SchemaBinding,
  SchemaBindingColumn,
  UIRenderProps,
  Mode,
  ReplacePlaceholdersOptions,
  AnchorAxis,
  ResolvedAnchorTarget,
};

// Anchor geometry — re-exported via `export from` to keep the public surface
// stable across the anchor extraction (Phase 4). New consumers can import
// directly from this module's exports.
export {
  ANCHOR_EPSILON,
  buildSchemaIndex,
  detectAnchorCycle,
  findAnchorReferentX,
  findAnchorReferentY,
  getAnchoredLayout,
  getSchemaAnchorIds,
  isAnchoredLayout,
  resolveAnchor,
  resolveAnchorX,
  resolveAnchorY,
  reverseAnchorOffsetX,
  reverseAnchorOffsetY,
} from './anchorGeometry.js';
export type {
  AnchoredLayoutRule,
  AnchoredSchema,
  SchemaIndex,
} from './anchorGeometry.js';
